In [2]:
import numpy as np
import matplotlib.pyplot as plt

Ohayo! I'm studying ML for a while and recently decided to Learn Deep Learning!<br>
I tried DL Specialization, but first 2 courses didn't really impress me (probably cuz I already know most of the stuff there).<br>
So that's why I decided to read:<br>
# **Neural Networks from Scratch**
<img src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1605802079l/55927899.jpg" width=10%><br>

By: <br>
Harrison Kinsley
aka
Sentdex<br>

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpgUcgi-2DcphvE6NDARjeaXeC2ZuIFduYyw&s" width=10%><br>

At least it contains code examples

In [3]:
# single neuron without numpy

inputs = [1, 2, 3]
weights = [2, 4, 6]
bias = 2

output = 0

assert(len(inputs) == len(weights))

for i in range(len(inputs)):
    output += weights[i] * inputs[i]

output += bias
print(output)

30


Nice... But it's just a single neuron<br>
Let's have a layer!

In [4]:
inputs = [1, 2, 3]

weights = [
    [2, 3, 4],
    [3, 4, 5],
    [4, 5, 6]
]

bias = [1, 2, 3]


output = [0, 0, 0]

for i in range(3):
    for j in range(len(inputs)):
        output[i] += weights[i][j] * inputs[j]
    output[i] += bias[i]
    

print(output)

[21, 28, 35]


Single neuron with NumPy<br>
I'm not retyping code from book, I'm writing my own

In [8]:
inputs = [1, 2, 3, 4]
weights = [1, 2, 3, 4]
bias = 1

output = np.dot(weights, inputs) + bias
print(output)

31


And it's super easy to build 1 Layer with NumPy vectorization

In [9]:
inputs = [1, 2, 3]

weights = [
    [2, 3, 4],
    [3, 4, 5],
    [4, 5, 6]
]

bias = [1, 2, 3]

output = np.dot(weights, inputs) + bias
print(output)

[21 28 35]


## **OneLiner!**

One Layer and Batch of Data!

In [17]:
# 3 samples with 3 features
data = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# 4 neurons with 3 weights
weights = [
    [1, 2, 3],
    [3, 4, 5],
    [5, 6, 7],
    [7, 8, 9]
]

biases = [1, 2, 3]

output = np.dot(weights, np.array(data).T) + biases

print(output)

[[ 15  34  53]
 [ 27  64 101]
 [ 39  94 149]
 [ 51 124 197]]
